### PR TITLE
Support for Multipart forms

### PR DESCRIPTION
**Pull request by Joannis**
Currently S4 doesn't support multipart forms. Multipart forms are, however, an essential part of websites and webservers and we'll need to discuss our approach towards it.

I've implemented Multipart form-parsing in Vapor yesterday and I think more libraries are to support this soon enough. Let alone libraries that I support it outside of my knowledge.

Multipart is made to support two kinds of information. Files and Input.
Input would refer to any form input that is not input[type="file"].
And both `input` as well as `file` can be an array.

HTML `select` (which supports multiple `option`s would be an example of an input array.
And `<input type="file" multiple="multiple" />` is an example of multiple files.

### CODE REVIEW

**Comment by LoganWright** [comment]
It might be nice if we use a type as opposed to a tuple for file:

```Swift
(filename: String?, mediaType: (type: String, subtype: String)?, data: Data)
```

Could be:

```Swift
extension MultipartForm {
    struct File {
        let filename: String?
        let mediaType: (type: String, subtype: String)? // might be worth a type here as well, but it's simpler than file, so feels less concerning
        let data: Data
    }
}
```

**Comment by paulofaria** [comment]
I'm not sure I see multipart in Open Swift. I think in general we should discuss the goal Open Swift is taking. Feels like we're becoming more like a standard library instead of protocol standards. I don't think this is bad. But it's different from what Open Swift was originally conceived. Actually there are some problems that might arise from the protocol/bare bones approach. Like this:

```swift
// Open Swift
struct Request { ... }

// Framework A
extension Request {
  var cookie: Cookie { ... }
}

// Framework B
extension Request {
  var cookie: Cookie { ... }
}

// Application
import FrameworkA
import FrameworkB

let cookie = request.cookie // trouble
```

So instead of making the projects compatible. They conflict with each other. I know this is not directly related to the PR in question. But it's related. So I'll create an issue so we can discuss this topic.

**Comment by Joannis** [comment]
@paulofaria I think multipart forms are simple enough to be standardizable. They are a standard in an RFC in the end.

But I think MultiPart forms are right where `Cookies` and `Headers` are..
They're standards for the internet, properly defined in an RFC Document by the IETF. I think that makes it S4-worthy by itself.

**Comment by tannernelson** [comment]
@Joannis would this be stored in a dictionary like `[String: Multipart]` where the `String` is the key?

**Comment by paulofaria** [comment]
multipart/form-data is a media type. If were going to bring these kinds of stuff to Open Swift, we need to think about the base first. In this case, `MediaType`. So I propose we discuss `MediaType` before we add any actua media type to Open Swift.

**Comment by Joannis** [comment]
@tannernelson I think it would.
@paulofaria I agree with that. Honestly didn't think about it that way!

**Comment by tannernelson** [comment]
Keeping this open for another week.

**Comment by paulofaria** [comment]
Closing for now..

**Pull request closed without merging**
