### PR TITLE
snapshot 06-06 and remove `become...`

### PR DESCRIPTION
**Pull request by tannernelson**
The `becomeAsync...` methods on `Body` are currently preventing us from moving to Snapshot 06-06. 

I'm proposing we remove these methods and remove all `become...` methods. This seems like it's something that should be implemented on the framework side and follows Open Swift's desire to have the "Minimum viable requirements".

In Vapor, we have to implement these methods ourselves to support the functionality we want with `Stream` anyway. I feel that other frameworks may also be doing this.

### CODE REVIEW

**Comment by tannernelson** [comment]
Fixes  #64

**Comment by noppoMan** [comment]
@tannernelson 

Sorry for my bugs...
I also agree with removing `becomeX` Cause 
> Open Swift's desire to have the "Minimum viable requirements".

But If I have chance to fix that.. How do you think this approach?
https://github.com/noppoMan/S4/commit/778b203fddb3d638d2bd8a4119c8507629f14326

I removed all mutating staffs from `becomeAsyncX...` But the behaviors are same as before.(Actually It is unnecessary mutation for `becomeAsyncX`.)
And It's not `become`(I mean there is no mutating) so We might need to change the method name to `toAsyncX` something like that

**Comment by tannernelson** [comment]
No worries, I think it makes more sense for these methods to be framework specific anyway.

**Comment by tannernelson** [comment]
Merging with 6 upvotes.

**Pull request merged**
