### PR TITLE
remove cookies

### PR DESCRIPTION
**Pull request by paulofaria**
`cookies` implementation on `Request` only allows retrieval of the cookies, there's no way to set cookies on the `Request` with the current implementation. I don't think we should add more than it's needed to Open Swift, and the `cookies` property can and should be implemented by other modules on top of Open Swift. So I propose we remove it. 😊

### CODE REVIEW

**Comment by tannernelson** [comment]
If we're removing it from Request then the application will depend on some sort of cookie middleware to implement that. In which case it would make sense to also remove them from `Response` so that the middleware can freely implement both.

**Comment by paulofaria** [comment]
you mean remove the `cookies` property or the `Cookies` type? we can't remove the `cookies` property, but we can remove the `Cookies` type. if we do remove the `Cookies` type from `S4` with the intent of implementation outside `S4`, then it makes sense to change `cookies` property to `var cookieHeaders: Set<String>`, so the `cookies` property name is available for usage in extensions.

**Comment by tannernelson** [comment]
Could we put that on the `Headers` struct?

```swift
struct Headers {
    var cookies: Set<String>
    ...
}
```

**Comment by paulofaria** [comment]
Hmm awesome idea! I think so.. I'll check later. to be sure.

**Comment by paulofaria** [comment]
should I update that?

**Comment by paulofaria** [comment]
@tannernelson what've you done here? haha

**Comment by paulofaria** [comment]
@tannernelson actually it's best for `cookieHeaders` to stay at `Response`. if it stays at `Header` then you would be able to set it on `Request`, and we only want it for `Response`.

**Comment by tannernelson** [comment]
Awh, okay :( That makes sense. It seems like it's going to be very easy for people to mess this up though. Like just putting headers in the Headers struct and not seeing the cookieHeaders set. 

Is there no way we could combine multiple set-cookie headers into one set-cookie header?

**Comment by paulofaria** [comment]
> Is there no way we could combine multiple set-cookie headers into one set-cookie header?

no, that's the thing. that's why we need a separate property. :(

>  Like just putting headers in the Headers struct and not seeing the cookieHeaders set.

not sure I followed haha

**Comment by tannernelson** [comment]
Merging with 6 upvotes.

**Pull request merged**
