### PR TITLE
make parsers take streams

### PR DESCRIPTION
**Pull request by paulofaria**

### CODE REVIEW

**Comment by tannernelson** [comment]
Why does this move from being synchronous to asynchronous?

**Comment by LoganWright** [comment]
I think this api makes more sense to return `throws -> Response` as opposed to the completion. The `@noescape` forces synchronicity in a way that feels a little unnatural.

```Swift
let response = try parser.parse(stream)
// do stuff w/ response
```

vs:

```Swift
var response: Response? = nil
try parser.parse {
    response = $0
}
// do stuff w/ response
```

If the latter syntax is preferred by an individuals library, they could easily add this:

```Swift
extension Parser {
    func parse(_ stream: Stream, with completion: @noescape (Response) throws -> Void) throws {
        let response = try parse(stream)
        completion(response)
    }
}
```

**Comment by paulofaria** [comment]
actually it wouldn't be asynchronous per se. the call would block and every time a new request is available, the callback would be called. until an error occurs. then it would unblock throwing the error. that's what we do with the old way, the only difference is that the loop happens outside the parsers, like so:

```swift
while true {
  let data = stream.receive(upTo: bufferSize)
  if let request = try parser.parse(data) { // if this fails the loop "unblocks"
    // do stuff with request
  }
}
```

this is what it would be now

```swift
try parser.parse(from: stream) { request in // if this fails the call unblocks
  // do stuff with request
}
```

**Comment by paulofaria** [comment]
but yeah I think we could make it:

```swift
while true {
  let request = try parser.parse(from: stream) // if this fails the loop "unblocks"
 // do stuff with request
}
```

but this way the parser has no control over the stream anymore.. so if anything is done to the stream during the `//do stuff with request` the next time `parse` is called the parser will probably fail.

**Comment by paulofaria** [comment]
that issue exists as of now.. and it didn't cause problems yet. so.. I think it's ok. I'm not sure, haha. but if we have problems we can always change it again.

**Comment by paulofaria** [comment]
thinking about removing `from`. only added to mirror:

```swift
public protocol ResponseSerializer {
    func serialize(_ response: Response, to stream: Stream) throws
}
```

but I'm starting to dislike it

**Comment by paulofaria** [comment]
removed it! feels like I'm schizophrenic, talking alone.. 🙃

```
while true {
  let request = try parser.parse(stream) // if this fails the loop "unblocks"
 // do stuff with request
}
```

**Comment by tannernelson** [comment]
Another point to consider would be 

```swift
let parser = Parser(stream: stream)
let request = try parser.parse()
let request = try parser.parse()
...
```

**Comment by tannernelson** [comment]
Merging with 4 upvotes.

**Pull request merged**
